# -*- mode: ruby -*-
# vi: set ft=ruby :
# Intruções de instalação
# $ vagrant box add precise-1204-64 http://10.0.16.80/files/precise-server-cloudimg-vagrant-amd64-disk1.box
# Depois rode:
# $ vagrant up
# Para atualizar o VirtualBoxGuestAdditions:
# $ vagrant plugin install vagrant-vbguest

Vagrant.configure("2") do |config|

  config.vm.box = "drupal_commerce_devkit"

  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210.box"

  config.vbguest.auto_update = false

  config.vm.provider :virtualbox do |vb|
    #vb.customize ["modifyvm", :id, "--cpus", "1"]
    #vb.gui = true
    vb.customize ["modifyvm", :id, "--memory", "1096"]
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
    vb.customize ["modifyvm", :id, "--pae", "on"]
  end

  config.vm.network :public_network

  config.vm.network :forwarded_port, guest: 80, host: 8080

  config.vm.network :private_network, ip: "33.33.33.2"

  config.vm.synced_folder "../../www/", "/var/www/", nfs: true

  config.vm.provision :puppet do |puppet|
     puppet.manifests_path = "manifests"
     puppet.module_path = "manifests/modules"
     puppet.manifest_file  = "base.pp"
  end

end
